### ISSUE TITLE
Add widget support

### ISSUE THREAD

**Issue by amberhinds** [wpaccessibility/wpaccessibilityday#1]
I'd like to have the the following sidebars/widget areas:

- Footer: 1 full-width widget area + 4-columns of widgets below it
- Pages: option of turning on a right sidebar on a page-by-page basis
- Posts: right sidebar on archive (different widget area than pages)

**Comment by joedolson** [comment]
Footer widgets are in place. Minimal CSS.

**Comment by joedolson** [comment]
Sidebar widgets in place; page template with sidebar enabled.
