### ISSUE TITLE
Use of centered text

### ISSUE THREAD

**Issue by joedolson** [wpaccessibility/wpaccessibilityday#10]
@amberhinds Centered text over about 3 lines is a poor experience for dyslexic readers or high magnification; I think we should reconsider its use on the home page.

**Comment by amberhinds** [comment]
I removed centering below the image. Do you think the H1 and Event date is problematic?

**Comment by joedolson** [comment]
They're probably OK. They'd be better if we could tighten up the text a little, e.g. "Let's make the web work for everyone" & "November 2-3, 2022"

I'm not sure how necessary it is to re-emphasize the virtual/free nature of the event.

**Comment by amberhinds** [comment]
Text shortened.
