### ISSUE TITLE
Create Microsponsors Shortcode

### ISSUE THREAD

**Issue by amberhinds** [wpaccessibility/wpaccessibilityday#16]
Please create a short code that can be used to display micro sponsor logos from the [Attendee Registration Gravity Form](https://wpaccessibility.day/wp-admin/admin.php?page=gf_entries&id=13).

Ideally, this should be similar to the [Sponsors output](https://wpaccessibility.day/sponsors/). It would be helpful to have an attribute that allows us to easily set the max height on the logos.

**Comment by amberhinds** [comment]
@joedolson Looking at your commit, I think this still needs styles to make the logos float next to one another, right?

I'm going to reopen this and reassign to myself - I can work on that this weekend.

**Comment by joedolson** [comment]
Styled & published.
