### ISSUE TITLE
Hard-coded registration URL

### ISSUE THREAD

**Issue by amberhinds** [wpaccessibility/wpaccessibilityday#17]
I'm not taking the time to figure this out now but opening an issue so I'm not the only one that knows about it.

I hard-coded the registration URL on the [WPCS sponsor single template](https://github.com/wpaccessibility/wpaccessibilityday/blob/master/wp-content/plugins/wpad-conference-schedule/templates/sponsor-template.php).

This isn't really a problem as long as we use /register or have a redirect in place for it, but it could be a problem in the future. I think that in the long run we should add a field for this in the [WPCS Settings page](https://wpaccessibility.day/wp-admin/options-general.php?page=wp-conference-schedule) and then replace that registration URL in the template.

**Comment by joedolson** [comment]
I added this field, but the sponsor-template.php in the repository doesn't match what I'm seeing on the site, so it seemed like maybe there was a missing commit somewhere. Leaving that for you to finish. The updates in this commit are already in the staging environment.

**Comment by amberhinds** [comment]
@joedolson I'm not seeing a difference between the file on the server and the file in the repo when I run a diff check.

**Comment by joedolson** [comment]
I think I see; this isn't the URL being used for 'create a free account here' at the bottom of the page, it's only used for the swag else.

**Comment by amberhinds** [comment]
Yes. It's just there. The one at the bottom of the page is coming via settings on the Gravity Form.

**Comment by amberhinds** [comment]
Did this get partially pushed?  The registration link on the schedule page is broken.  When I look at the functions file I see:
`$output = "<div class='wpad-callout'><p><a href='" . esc_url( get_option( 'wpcs_field_registration' ) ) . "'>Register for WP Accessibility Day!</a> $append</p></div>";`

But I don't see the field in the WPCS settings. I'm not 100% sure how to fix this.

**Comment by joedolson** [comment]
I may have uploaded the whole template directory when I updated the session
time format.

If you upload the current inc directory the setting should be there.

Sorry about that; but I'm not able to do it right now.
