### ISSUE TITLE
Add our theme colors to the block color palatte

### ISSUE THREAD

**Issue by amberhinds** [wpaccessibility/wpaccessibilityday#6]
These would be handy to have available without having to type the hex code:

--color-dark-purple: #7F1177;
    --color-light-purple: #EFE6F0;
    --color-dark-blue: #115A7F;
    --color-light-blue: #e4eff5;

**Comment by joedolson** [comment]
Hmm. Thought I'd already done that here: https://github.com/wpaccessibility/wpaccessibilityday/blob/23b9a94e0a819cb4fed02746ae86a63ae385a36f/wp-content/themes/wp-a11y-day/functions.php#L82, but I didn't check it.

**Comment by joedolson** [comment]
Well, that's weird. There are colors available, but they aren't the ones I set up. I bet there's some code somewhere overriding that. I'll find it.

**Comment by joedolson** [comment]
Fixed in https://github.com/wpaccessibility/wpaccessibilityday/commit/96bb21d8c02e9886818c62672123337b734d5a54
