### ISSUE TITLE
Rewrite the Speakers slug to people

### ISSUE THREAD

**Issue by amberhinds** [wpaccessibility/wpaccessibilityday#7]
I don't want to do this in WPCS Pro, but since we might want to add organizers and volunteers with the speakers post type, I think it makes sense to rewrite the slug to /people/ instead of /speakers/ with a filter in our theme.

Something [like this](https://developer.wordpress.org/reference/hooks/register_post_type_args/#user-contributed-notes) is what I was thinking.  Let me know what you think about this @joedolson

**Comment by joedolson** [comment]
Clarifying: still using the WPCS post type, but filtering the slug?

**Comment by amberhinds** [comment]
Yes, that's what I was thinking. Just changing the appearance of it in the address bar so it doesn't say speakers.

**Comment by amberhinds** [comment]
Then we can still use everything else about the speakers CPT but not have the URL look wrong if we also use it for volunteers.
