### ISSUE TITLE
Latest News layout

### ISSUE THREAD

**Issue by joedolson** [wpaccessibility/wpaccessibilityday#9]
I'm not sure what the intent is on the home page 'Latest News'; it may make more sense when there are more posts, but it's strange at the moment. It could use more work, especially on mobile; but I wasn't sure of the intent.

![image](https://user-images.githubusercontent.com/1686451/166155195-888eb84d-0d50-4193-91bd-a2d7d424a845.png)
Desktop

![image](https://user-images.githubusercontent.com/1686451/166155216-f311bb47-90b6-4084-9134-6ba716552f00.png)
Small screen

**Comment by amberhinds** [comment]
This has been resolved with the addition of two more blog posts and styles to make is three columns
